export const FETCHING_POPULAR = "FETCHING_POPULAR";
export const FETCHING_POPULAR_SUCCESS = "FETCHING_POPULAR_SUCCESS";
export const FETCHING_NEW = "FETCHING_NEW";
export const FETCHING_NEW_SUCCESS = "FETCHING_NEW_SUCCESS";
export const FETCHING_MOVIE = "FETCHING_MOVIE";
export const FETCHING_MOVIE_SUCCESS = "FETCHING_MOVIE_SUCCESS";
export const FETCHING_MOVIE_ERROR = "FETCHING_MOVIE_ERROR";
